export const currencyName = [
    {key: "aed", val: "United Arab Emirates Dirham"},
    {key: "byn", val: "Belarusian ruble"},
    {key: "cuc", val: "Cuban convertible peso"},
    {key: "ern", val: "Eritrean nakfa"},
    {key: "fkp", val: "Falkland Islands pound"},
    {key: "ggp", val: "Guernsey pound"},
    {key: "jep", val: "Jersey pound"},
    {key: "gip", val: "Gibraltar pound"},
    {key: "imp", val: "Manx pound"},
    {key: "ssp", val: "South Sudanese pound"},
    {key: "std", val: "Sao Tome dobra"},
    {key: "stn", val: "Sao Tome and Principe dobra"},
    {key: "ves", val: "Venezuelan bolivar"},
    {key: "wst", val: "Samoan tala"},
    {key: "xag", val: "Silver Ounce"},
    {key: "xau", val: "Gold ounce"},
    {key: "xdr", val: "Special Drawing Rights"},
    {key: "xpd", val: "Palladium Ounce"},
    {key: "xpt", val: "Platinum Ounce"},
    {key: "zwl", val: "Zimbabwean dollar"},   
    {key: "afn", val: "Afghan afghani"},
    {key: "all", val: "Albanian lek"},
    {key: "amd", val: "Armenian dram"},
    {key: "ang", val: "Netherlands Antillean Guilder"},
    {key: "aoa", val: "Angolan kwanza"},
    {key: "ars", val: "Argentine peso"},
    {key: "aud", val: "Australian dollar"},
    {key: "awg", val: "Aruban florin"},
    {key: "azn", val: "Azerbaijani manat"},
    {key: "bam", val: "Bosnia-Herzegovina Convertible Mark"},
    {key: "bbd", val: "Bajan dollar"},
    {key: "bch", val: "Bitcoin Cash"},
    {key: "bdt", val: "Bangladeshi taka"},
    {key: "bgn", val: "Bulgarian lev"},
    {key: "bhd", val: "Bahraini dinar"},
    {key: "bif", val: "Burundian Franc"},
    {key: "bmd", val: "Bermudan dollar"},
    {key: "bnd", val: "Brunei dollar"},
    {key: "bob", val: "Bolivian boliviano"},
    {key: "brl", val: "Brazilian real"},
    {key: "bsd", val: "Bahamian dollar"},
    {key: "btc", val: "Bitcoin"},
    {key: "btn", val: "Bhutan currency"},
    {key: "bwp", val: "Botswanan Pula"},
    {key: "byr", val: "Belarusian ruble"},
    {key: "bzd", val: "Belize dollar"},
    {key: "cad", val: "Canadian dollar"},
    {key: "cdf", val: "Congolese franc"},
    {key: "chf", val: "Swiss franc"},
    {key: "clf", val: "Chilean Unit of Account (UF)"},
    {key: "clp", val: "Chilean peso"},
    {key: "cnh", val: "Chinese Yuan (offshore)"},
    {key: "cny", val: "Chinese Yuan"},
    {key: "cop", val: "Colombian peso"},
    {key: "crc", val: "Costa Rican Colón"},
    {key: "cup", val: "Cuban Peso"},
    {key: "cve", val: "Cape Verdean escudo"},
    {key: "czk", val: "Czech koruna"},
    {key: "djf", val: "Djiboutian franc"},
    {key: "dkk", val: "Danish krone"},
    {key: "dop", val: "Dominican peso"},
    {key: "dzd", val: "Algerian dinar"},
    {key: "egp", val: "Egyptian pound"},
    {key: "etb", val: "Ethiopian birr"},
    {key: "eth", val: "Ether"},
    {key: "eur", val: "Euro"},
    {key: "fjd", val: "Fijian dollar"},
    {key: "gbp", val: "Pound sterling"},
    {key: "gel", val: "Georgian lari"},
    {key: "ghs", val: "Ghanaian cedi"},
    {key: "gmd", val: "Gambian dalasi"},
    {key: "gnf", val: "Guinean franc"},
    {key: "gqe", val: "Central African CFA franc"},
    {key: "gtq", val: "Guatemalan quetzal"},
    {key: "gyd", val: "Guyanaese Dollar"},
    {key: "hkd", val: "Hong Kong dollar"},
    {key: "hnl", val: "Honduran lempira"},
    {key: "hrk", val: "Croatian kuna"},
    {key: "htg", val: "Haitian gourde"},
    {key: "huf", val: "Hungarian forint"},
    {key: "idr", val: "Indonesian rupiah"},
    {key: "ils", val: "Israeli New Shekel"},
    {key: "inr", val: "Indian rupee"},
    {key: "iqd", val: "Iraqi dinar"},
    {key: "irr", val: "Iranian rial"},
    {key: "isk", val: "Icelandic króna"},
    {key: "jmd", val: "Jamaican dollar"},
    {key: "jod", val: "Jordanian dinar"},
    {key: "jpy", val: "Japanese yen"},
    {key: "kes", val: "Kenyan shilling"},
    {key: "kgs", val: "Kyrgystani Som"},
    {key: "khr", val: "Cambodian riel"},
    {key: "kmf", val: "Comorian franc"},
    {key: "kpw", val: "North Korean won"},
    {key: "krw", val: "South Korean won"},
    {key: "kwd", val: "Kuwaiti dinar"},
    {key: "kyd", val: "Cayman Islands dollar"},
    {key: "kzt", val: "Kazakhstani tenge"},
    {key: "lak", val: "Laotian Kip"},
    {key: "lbp", val: "Lebanese pound"},
    {key: "lkr", val: "Sri Lankan rupee"},
    {key: "lrd", val: "Liberian dollar"},
    {key: "lsl", val: "Lesotho loti"},
    {key: "ltc", val: "Litecoin"},
    {key: "lyd", val: "Libyan dinar"},
    {key: "mad", val: "Moroccan dirham"},
    {key: "mdl", val: "Moldovan leu"},
    {key: "mga", val: "Malagasy ariary"},
    {key: "mkd", val: "Macedonian denar"},
    {key: "mmk", val: "Myanmar Kyat"},
    {key: "mnt", val: "Mongolian tugrik"},
    {key: "mop", val: "Macanese pataca"},
    {key: "mru", val: "Mauritanian Ouguiya (1973–2017)"},
    {key: "mur", val: "Mauritian rupee"},
    {key: "mvr", val: "Maldivian rufiyaa"},
    {key: "mwk", val: "Malawian kwacha"},
    {key: "mxn", val: "Mexican peso"},
    {key: "myr", val: "Malaysian ringgit"},
    {key: "mzm", val: "Mozambican metical"},
    {key: "mzn", val: "Mozambican Metical"},
    {key: "nad", val: "Namibian dollar"},
    {key: "ngn", val: "Nigerian naira"},
    {key: "nio", val: "Nicaraguan córdoba"},
    {key: "nok", val: "Norwegian krone"},
    {key: "npr", val: "Nepalese rupee"},
    {key: "nzd", val: "New Zealand dollar"},
    {key: "omr", val: "Omani rial"},
    {key: "pab", val: "Panamanian balboa"},
    {key: "pen", val: "Sol"},
    {key: "pgk", val: "Papua New Guinean kina"},
    {key: "php", val: "Philippine peso"},
    {key: "pkr", val: "Pakistani rupee"},
    {key: "pln", val: "Poland złoty"},
    {key: "pyg", val: "Paraguayan guarani"},
    {key: "qar", val: "Qatari Rial"},
    {key: "ron", val: "Romanian leu"},
    {key: "rsd", val: "Serbian dinar"},
    {key: "rub", val: "Russian ruble"},
    {key: "rwf", val: "Rwandan Franc"},
    {key: "sar", val: "Saudi riyal"},
    {key: "sbd", val: "Solomon Islands dollar"},
    {key: "scr", val: "Seychellois rupee"},
    {key: "sdg", val: "Sudanese pound"},
    {key: "sek", val: "Swedish krona"},
    {key: "sgd", val: "Singapore dollar"},
    {key: "shp", val: "Saint Helena pound"},
    {key: "sll", val: "Sierra Leonean leone"},
    {key: "sos", val: "Somali shilling"},
    {key: "srd", val: "Surinamese dollar"},
    {key: "svc", val: "Salvadoran Colón"},
    {key: "syp", val: "Syrian pound"},
    {key: "szl", val: "Swazi lilangeni"},
    {key: "thb", val: "Thai baht"},
    {key: "tjs", val: "Tajikistani somoni"},
    {key: "tmt", val: "Turkmenistan manat"},
    {key: "tnd", val: "Tunisian dinar"},
    {key: "top", val: "Tongan Paʻanga"},
    {key: "try", val: "Turkish lira"},
    {key: "ttd", val: "Trinidad & Tobago Dollar"},
    {key: "twd", val: "New Taiwan dollar"},
    {key: "tzs", val: "Tanzanian shilling"},
    {key: "uah", val: "Ukrainian hryvnia"},
    {key: "ugx", val: "Ugandan shilling"},
    {key: "usd", val: "United States dollar"},
    {key: "uyu", val: "Uruguayan peso"},
    {key: "uzs", val: "Uzbekistani som"},
    {key: "vef", val: "Sovereign Bolivar"},
    {key: "vnd", val: "Vietnamese dong"},
    {key: "vuv", val: "Vanuatu vatu"},
    {key: "xaf", val: "Central African CFA franc"},
    {key: "xcd", val: "East Caribbean dollar"},
    {key: "xof", val: "West African CFA franc"},
    {key: "xpf", val: "CFP franc"},
    {key: "yer", val: "Yemeni rial"},
    {key: "zar", val: "South African rand"},
    {key: "zmw", val: "Zambian Kwacha"}
]